import React from 'react';
import { Card, Space, Typography, Divider, Tag, List, Empty } from 'antd';
import {
  FileTextOutlined,
  ClockCircleOutlined,
  CheckCircleOutlined,
  ExperimentOutlined
} from '@ant-design/icons';
import './ReportDisplay.css';

const { Text, Title, Paragraph } = Typography;

/**
 * AI报告展示组件
 * @param {Object} report - 生成的报告数据
 */
const ReportDisplay = ({ report }) => {
  if (!report) {
    return (
      <Card className="report-display-card">
        <Empty
          description="No report generated yet"
          image={Empty.PRESENTED_IMAGE_SIMPLE}
        />
      </Card>
    );
  }

  return (
    <Card
      title={
        <Space>
          <FileTextOutlined style={{ color: '#059669' }} />
          <span style={{ color: '#047857' }}>Generated Medical Report</span>
        </Space>
      }
      className="report-display-card"
    >
      <div className="report-display-content">
        {/* 报告标题 */}
        <div className="report-header">
          <Title level={3} style={{ margin: 0, color: '#1e40af' }}>
            {report.title}
          </Title>
          <Space size="small" style={{ marginTop: '8px' }}>
            <ClockCircleOutlined style={{ color: '#6b7280' }} />
            <Text type="secondary">{report.timestamp}</Text>
          </Space>
        </div>

        <Divider />

        {/* 诊断信息 */}
        <div className="report-section">
          <div className="section-header">
            <Text strong className="section-title">Diagnosis:</Text>
            <Tag color="orange" className="diagnosis-tag">
              {report.diagnosis}
            </Tag>
          </div>
          <div className="confidence-info">
            <Text type="secondary">
              Confidence: <strong style={{ color: '#10b981' }}>{report.confidence}%</strong>
            </Text>
          </div>
        </div>

        <Divider />

        {/* 详细分析 */}
        <div className="report-section">
          <Text strong className="section-title">Detailed Analysis:</Text>
          <Paragraph className="analysis-box" style={{ whiteSpace: 'pre-line' }}>
            {report.detailedAnalysis}
          </Paragraph>
        </div>

        <Divider />

        {/* 医疗建议 */}
        <div className="report-section">
          <Text strong className="section-title">Medical Recommendations:</Text>
          <List
            dataSource={report.recommendations}
            renderItem={(item) => (
              <List.Item className="recommendation-list-item">
                <CheckCircleOutlined style={{ color: '#10b981', marginRight: '8px' }} />
                <Text>{item}</Text>
              </List.Item>
            )}
            className="recommendations-list"
          />
        </div>

        {/* 自定义备注 */}
        {report.customNotes && (
          <>
            <Divider />
            <div className="report-section">
              <Text strong className="section-title">Custom Notes:</Text>
              <Paragraph className="custom-notes-box">
                {report.customNotes}
              </Paragraph>
            </div>
          </>
        )}

        <Divider />

        {/* 报告生成信息 */}
        <div className="report-footer">
          <Space>
            <ExperimentOutlined style={{ color: '#8b5cf6' }} />
            <Text type="secondary">
              Generated by: <strong>{report.generatedBy}</strong>
            </Text>
          </Space>
        </div>
      </div>
    </Card>
  );
};

export default ReportDisplay;
